version: '2'

services:

  proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  dnsdock:
#    image: tonistiigi/dnsdock:amd64-1.13.1
    image: aacebedo/dnsdock:v1.15.0-amd64
    ports:
      - 172.17.0.1:53:53/udp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      
  db:
    container_name: db
    image: postgres
    env_file: .env

  maven:
    image: maven:3.3.9-jdk-8
    volumes:
      - ./checklistbank:/usr/src/mymaven
      - ./settings.xml:/root/.m2/settings.xml
      - ./repository:/root/.m2/repository

  rabbit:
    image: rabbitmq
    env_file: .env
    hostname: rabbit
    container_name: rabbit

  solr:
    image: solr
    env_file: .env
    hostname: solr
    container_name: solr

  ws:
    image: nginx

  clbws:
    image: dina/clbws:v0.1
    environment:
      - VIRTUAL_HOST=clbws
      - DNSDOCK_ALIAS=clbws
    depends_on:
      - db
      - solr
    ports:
      - 9000
      - 9001

  clbcli:
    image: dina/clbcli:v0.1
    env_file: .env
    depends_on:
      - db
      - solr
      - rabbit
