version: '2'

services:

  elk:
    image: advantageous/elk:0.1
    hostname: elk
    container_name: elk
    ports:
      - "5601:5601"
    command: /usr/local/bin/start.sh

  db:
    image: gbifs/clbdb:2.47-SNAPSHOT
    container_name: db
    env_file: .env
    ports:
      - "5432:5432"

  rabbit:
    image: rabbitmq:3.6-management
    env_file: .env
    hostname: rabbit
    container_name: rabbit
    ports:
      - "15672:15672"

  solr:
    image: gbifs/clbsolr:2.47-SNAPSHOT
    env_file: .env
    hostname: solr
    container_name: solr
    ports:
      - "8983:8983"
    environment:
      - VERBOSE=yes

  varnish:
    image: million12/varnish
    env_file: .env
    hostname: varnish
    container_name: varnish
    environment:
      - VCL_CONFIG=/etc/clb/default.vcl
    ports:
      - "80:80"
    volumes_from:
      - ws
    depends_on:
      - ws

  ws:
    image: gbifs/clbws:2.47-SNAPSHOT
    container_name: ws
    hostname: ws
    volumes:
      - /etc/clb
    depends_on:
      - db
      - solr
      - elk
    ports:
      - "9000:9000"
      
#  nub-ws:
#    image: gbifs/nubws:2.47-SNAPSHOT
#    container_name: nubws
#    hostname: nubws
#    depends_on:
#      - db
#      - elk
#    ports:
#      - 9002
#      - 9003

  clb-analyzer:
    image: gbifs/clbcli:2.47-SNAPSHOT
    env_file: .env
    depends_on:
      - db
      - solr
      - rabbit
      - elk
    environment:
      - COMMAND=analysis
      - MAX_HEAP=256M
    volumes_from:
      - clb-crawler

  clb-crawler:
    image: gbifs/clbcli:2.47-SNAPSHOT
    env_file: .env
    depends_on:
      - db
      - solr
      - rabbit
      - elk
    environment:
      - COMMAND=crawler
      - MAX_HEAP=256M
    volumes:
      - /usr/local/clb/data

  clb-importer:
    image: gbifs/clbcli:2.47-SNAPSHOT
    env_file: .env
    depends_on:
      - db
      - solr
      - rabbit
      - elk
    environment:
      - COMMAND=importer
      - MAX_HEAP=2G
    volumes_from:
      - clb-crawler

  clb-matcher:
    image: gbifs/clbcli:2.47-SNAPSHOT
    env_file: .env
    depends_on:
      - db
      - solr
      - rabbit
      - elk
    environment:
      - COMMAND=dataset-matcher
      - MAX_HEAP=1G
    volumes_from:
      - clb-crawler

  clb-normalizer:
    image: gbifs/clbcli:2.47-SNAPSHOT
    env_file: .env
    depends_on:
      - db
      - solr
      - rabbit
      - elk
    environment:
      - COMMAND=normalizer
      - MAX_HEAP=3G
    volumes_from:
      - clb-crawler

  clb-admin:
    image: gbifs/clbcli:2.47-SNAPSHOT
    env_file: .env
    depends_on:
      - db
      - solr
      - rabbit
      - elk
    command: /bin/bash
    environment:
      - MAX_HEAP=256M
    volumes_from:
      - clb-crawler
