messaging:
  host: rabbit
  virtualHost: /uat
  username: clb
  password: passw0rd12
neo:
  neoRepository: /usr/src/myapp/neo
  mappedMemory: 8192
  batchSize: 10000
clb:
  serverName: db
  databaseName: clb
  user: clb
  password: passw0rd12
  maximumPoolSize: 8
  minimumIdle: 0
  idleTimeout: 60000
  connectionTimeout: 2000
registry:
  wsUrl: http://registry/v1
validate: true
runAssertions: false
groupBasionyms: true
keepLonelyAutonyms: false
keepEmptyImplicitNames: false
autoImport: false
reportDir: /usr/src/myapp/logs/nub
