messaging:
  host: rabbit
  virtualHost: /uat
  username: clb
  password: passw0rd12
registry:
  wsUrl: http://registry/v1
  user: clb
  password: passw0rd12
clb:
  serverName: clbws
  databaseName: clb
  user: clb
  password: passw0rd12
  maximumPoolSize: 4
  connectionTimeout: 2000
  minimumIdle: 0
  idleTimeout: 60000
zookeeper:
  connectionString: zoo1,zoo2,zoo3
  namespace: uat_crawler
neo:
  neoRepository: /usr/src/myapp/neo
archiveRepository: /usr/src/myapp/storage/dwca
