messaging:
  host: rabbit
  virtualHost: /
  username: guest
  password: guest
registry:
  wsUrl: /usr/src/clb/datasets.txt
clb:
  serverName: db
  databaseName: clb
  user: postgres
  password: passw0rd12
  maximumPoolSize: 4
  connectionTimeout: 2000
  minimumIdle: 0
  idleTimeout: 60000
neo:
  neoRepository: /usr/src/clb/neo
archiveRepository: /usr/src/clb/dwca
